language: android
dist: trusty
env:
  global:
  - REPO=t-e-l/tel-keyboard
  - APK_NAME="TEL:Keyboard"
  - ANDROID_API=30
  - ANDROID_BUILD_API=30.0.1
script:
- "./gradlew :app:assembleRelease"
android:
  components:
  - build-tools-${ANDROID_BUILD_API}
  - android-${ANDROID_API}
  licenses:
  - android-sdk-license-.+
  - android-ndk-license-.+
  - android-sdk-preview-license-.+
  - google-gdk-license-.+
before_install:
- openssl aes-256-cbc -K $encrypted_c80f59e584b7_key -iv $encrypted_c80f59e584b7_iv
  -in keystore.jks.enc -out keystore.jks -d
- mkdir -p $ANDROID_HOME/licenses
- echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
- echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
- echo y | sdkmanager "platforms;android-${ANDROID_API}"

before_deploy:
- find . -name '*.apk'

