language: android
dist: trusty
env:
  global:
  - REPO=t-e-l/tel-keyboard
  - APK_NAME="TEL:Keyboard"
android:
  components:
    - build-tools-30.0.1
    - android-30
  licenses:
  - android-sdk-license-.+
  - android-ndk-license-.+
  - android-sdk-preview-license-.+
  - google-gdk-license-.+